version: "3.8"
volumes:
  data-volume: {}
  exclude:
services:
  db:
    container_name: "db"
    image: "mysql:5.7"
    volumes:
      - data-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=company
      - MYSQL_ALLOW_EMPTY_PASSWORD=Y
  nodejs:
    container_name: "nodejs"
    build: "./nodejs"
    depends_on:
      - db
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./nodejs/:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    links:
      - "db"



