version: "3.8"
services:
  db:
    container_name: "db"
    image: "mysql:5.7"
    volumes:
      - ./db/storage:/var/lib/mysqll
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=company
      - MYSQL_DATABASE=OriginalScenario
      - MYSQL_ALLOW_EMPTY_PASSWORD=Y
  redis: 
    image: "redis:alpine"
  nodejs:
    container_name: "nodejs"
    build: "./nodejs"
    depends_on:
      - redis
      - db
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./nodejs:/usr/src/app
    links:
      - "db"



